### ISSUE TITLE
Can't get this thing working

### ISSUE THREAD

**Issue by l1t7l3ph0o7** [tobykurien/rpi_lcars#5]
Sorry but I just can't figure this out, I'm stumped 
from what I understand I should just clone the repository to /home/pi/rpi_lcars
then open a terminal and move to /home/pi/rpi_lcars/app and type python lcars.py i get:

> Traceback (most recent call last):
>   File "lcars.py", line 1, in <module>
>     from screens.authorize import ScreenAuthorize
>   File "/home/pi/rpi_lcars/app/screens/authorize.py", line 6, in <module>
>     from ui.widgets.gifimage import LcarsGifImage
>   File "/home/pi/rpi_lcars/app/ui/widgets/gifimage.py", line 1, in <module>
>     from ui.utils.gif_image import GIFImage
>   File "/home/pi/rpi_lcars/app/ui/utils/gif_image.py", line 3, in <module>
>     from PIL import Image
> ImportError: No module named PIL
> 
I have a pi2, I'm also using a 30 in hdmi monitor if that makes a difference

**Comment by kjcole** [comment]
On Sat, Aug 27, 2016 at 1:45 AM, l1t7l3ph0o7 <notifications@github.com> wrote:
>
> ImportError: No module named PIL

PIL is the Python Imaging Library (https://pypi.python.org/pypi/PIL)
and it is not installed on your system.  I don't have my trusty Pi
sitting in front of me. So I don't have the exact package name, but
try this:

    sudo apt install most

(because it's a MUCH nicer pager than less, and has been around since
the days of the mainframes.  Written by Jon Davis of MIT.)

Now, to search for the package name:

    apt-cache search pil | sort | most

and use your cursor keys to scroll down. If you see python-pillow or
python-pil, and it describes it as the Python Imaging Library.
success. Type "Q" to quit most and install PIL with:

    sudo apt install python-pil       (or python-pillow)

If, for some reason, it's not nicely packaged as a Raspbian package
and does not appear in the above list, you can use Python's installer
tool, pip (https://pypi.python.org/pypi/pip/) to install it instead
with:

    sudo -H pip install Pillow

**Comment by l1t7l3ph0o7** [comment]
Found it! it was python-Imaging for anyone who is interested (maybe change the list of dependencies or add clarification to the readme?)
